culturalRingRoad/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('home.urls')),
    path('places/', include('place.urls')),
    path('events/', include('event.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from . import views
from django.urls import path

app_name = "event"

urlpatterns = [
    path('', views.event, name="event"),
    path('<slug:slug>/', views.event_detail, name="event_detail")
]

home/urls.py
from . import views
from django.urls import path

app_name = "home"

urlpatterns = [
    path('', views.index, name="index"),
    path('gallery/', views.gallery, name="gallery"),
]

place/urls.py
from . import views
from django.urls import path

app_name = "place"

urlpatterns = [
    path('', views.place, name="place"),
    path('<slug:slug>', views.place_detail, name="placeDetail")
]

event/models.py
from django.db import models
from place.models import Place
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


class Event(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField()
    image = models.ImageField(upload_to='Event/')
    place = models.ManyToManyField(Place, related_name="events")
    duration = models.IntegerField(help_text="duration of event in Days")
    start_date = models.DateField()
    short_description = models.TextField()
    long_description = RichTextUploadingField(default=None)
    active = models.BooleanField(default=False)
    running = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_locations(self):
        pass

    def get_absolute_url(self):
        return reverse("event:event_detail", kwargs={"slug": self.slug})

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.


class Slider(models.Model):
    image = models.ImageField(upload_to='slider/')
    caption = models.CharField(max_length=250)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = "slider"
        verbose_name_plural = "sliders"

    def __str__(self):
        return self.caption


class About(models.Model):
    short_content = models.TextField()
    long_description = RichTextUploadingField(default=None)
    long_description_nepali = RichTextUploadingField(default=None)

    def __str__(self):
        return self.short_content


class Social(models.Model):
    facebook = models.URLField(
        "Facebook Page", max_length=200, blank=True, null=True)
    youtube = models.URLField(
        "Youtube Channel", max_length=200, blank=True, null=True)

    def __str__(self):
        return self.facebook


class Contact(models.Model):
    address = models.CharField(max_length=200)
    phone_number1 = models.CharField("Primary Phone number", max_length=10)
    phone_number2 = models.CharField(
        "Secondary Phone number", max_length=10, blank=True, null=True)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return self.address

place/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse


class Place(models.Model):
    index = models.IntegerField(unique=True)
    name = models.CharField(max_length=250)
    slug = models.SlugField(
        unique=True, help_text="Please Enter a text in all small letters and use '-' instead of spaces if required.")
    image = models.ImageField(upload_to='places/')
    short_description = models.TextField()
    long_description = RichTextUploadingField(default=None)
    long_description_nepali = RichTextUploadingField(
        default=None, blank=True, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("place:placeDetail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["index"]
        verbose_name = "Place"
        verbose_name_plural = "Places"


class Gallery(models.Model):
    title = models.CharField(max_length=350)
    video_url = models.URLField(
        max_length=200, help_text="Place Youtube embed url")
    active = models.BooleanField(default=True)
    uploaded_at = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.title

event/views.py
from django.shortcuts import render
from .models import Event
# Create your views here.


def event(request):
    events = Event.objects.filter(active=True)
    running_events = Event.objects.filter(active=True, running=True)
    not_running_events = Event.objects.filter(active=True, running=False)
    context = {
        'events': events,
        'running_events': running_events,
        'not_running_events': not_running_events,
        "event_active": True
    }
    return render(request, 'event/events.html', context)


def event_detail(request, slug=None):
    instance = Event.objects.get(slug=slug)
    context = {
        "instance": instance,
        "event_active": True
    }
    return render(request, 'event/event_detail.html', context)

home/views.py
from django.shortcuts import render
from .models import Slider, About
from place.models import Place, Gallery


def coming_soon(request):
    launchDate = "2019/05/17"
    context = {
        "launchDate": launchDate
    }
    return render(request, 'home/coming-soon.html', context)


def index(request):
    slider_list = Slider.objects.all()
    places = Place.objects.all()
    # about = About.objects.all()
    context = {
        "slider_list": slider_list,
        "places": places,
        # "about": about and about[0],
        "home_active": True
    }
    return render(request, 'home/index.html', context)


def gallery(request):
    gallery = Gallery.objects.filter(active=True)
    context = {
        'gallery': gallery,
        'gallery_active': True
    }
    return render(request, 'home/gallery.html', context)

place/views.py
from django.shortcuts import render
from .models import Place
# Create your views here.


def place(request):
    places = Place.objects.all()
    context = {
        "places": places,
        "place_active": True
    }
    return render(request, 'place/place.html', context)


def place_detail(request, slug=None):
    instance = Place.objects.get(slug=slug)

    context = {
        "instance": instance,
        "place_active": True
    }

    return render(request, 'place/detail.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name=description content= />
    <meta name=keywords content= />
    <meta name=author content= />
    {% block meta_links %}
    <!-- meta data stuffs are included here -->
    {% endblock %}
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block style_links %}

    <!-- style links are included here -->
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top">
        <a class="navbar-brand" href="/">Cultural Ring Road</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item {% if home_active %}active{% endif %}">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if event_active %}active{% endif %}">
                    <a class="nav-link" href="{% url 'event:event' %}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if place_active %}active{% endif %}" href="{% url 'place:place' %}">Places</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if gallery_active %}active{% endif %}"
                        href="{% url 'home:gallery' %}">Gallery</a>
                </li>

            </ul>
        </div>
    </nav>
    {% block content %}

    {% endblock %}
    <div class="upper-footer">
        <div class="container pt-5 pb-4 ">
            <div class="row">
                <div class="col-xs-12 col-md-5">
                    <h4 class="mb-3">About</h4>
                    <p class="text-justify">{{about.short_content}}</p>
                </div>
                <div class="col-xs-12 col-md-3 footer-explore__wrapper">
                    <h4 class="mb-3">Explore</h4>
                    <a href="{% url 'place:place' %}">
                        <p class="explore-item">Places</p>
                    </a>
                    <a href="{% url 'event:event' %}">
                        <p class="explore-item">Events</p>
                    </a>
                </div>
                <div class="col-xs-12 col-md-4">
                    <h4 class="mb-3">Contact</h4>
                    <p><strong>पर्यटकिय पुर्वाधार तथा सुचना केन्द्र उपभोक्ता समिति</strong></p>
                    <p><i class="fa fa-map-marker mr-3"></i>{{contact.address}}</p>
                    {% if contact.phone_number1 %}<p><span
                            class="fa fa-phone mr-3"></span>{{contact.phone_number1}}{% if contact.phone_number2 %},
                        {{contact.phone_number2}}{% endif %}
                    </p>
                    {% endif %}
                    {% if contact.email %}
                    <p>
                        <span class="fa fa-envelope mr-3"></span>{{contact.email}}
                    </p>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <footer class="mx-auto">
        <span>&copy; paryatakiya Chakrapath Upavokta Samiti, </span> <span id="date"></span> <span class="mx-3">|</span>
        <span>Made
            with <span class="mx-1" style="color: red">&hearts;</span> from <a class="ml-1"
                href="https://techkunja.com.np" target="_blank">Tech Kunja</a> </span>
    </footer>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

    <script src="{% static 'js/main.js' %}"></script>
    {% block script_links %} {% endblock %}
    <script>
        $('#date').text(new Date().getFullYear());
    </script>
    {% block scripts %}

    {% endblock %}
</body>

</html>

templates/event/event_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | Event Detail {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
{% endblock %}

{% block content %}
<section class="page-content__wrapper">
    <img src="{{instance.image.url}}" alt="{{instance.name}}" class="event-detail-image">
    <div class=" container">
        <div class="container mt-5">
            <div class="row">
                <div class="col">
                    {{instance.long_description|safe}}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block script_links %}
{% endblock %}

{% block scripts %}
{% endblock %}

templates/event/events.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | Events {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
{% endblock %}


{% block content %}
<section class="bg-light page-content__wrapper">
    <div class="container pt-5">
        <div class="row">
            <div class="col">
                <h1>Current Events</h1>
            </div>
        </div>
        <div class="row mt-3">
            {% for event in running_events %}
            <div class="col-xs-12 col-sm-6 mb-4 blog-showcase">
                <a href="{{event.get_absolute_url}}">
                    <div class="content-box boxed blog-box">
                        <div style="position: relative;">
                            <img src="{{event.image.url}}" class="blog-image" alt="{{blog.title}}">
                            <div class="blog-date">
                                <span>{{event.start_date|date:"d"}} ram</span>
                                <span>{{event.start_date|date:"M Y"}}</span>
                            </div>
                        </div>
                        <div class="p-3">
                            <h4 class="mb-3">{{event.name}}</h4>
                            <i class="fas fa-bookmark"></i>
                            <span class="ml-1 mr-5">
                                {% for place in event.place.all %}
                                <span class="event_places">{{place.name}}</span>
                                {% endfor %}
                            </span>
                            <i class="fas fa-calendar"></i> <span>{{event.duration}} Days</span>
                            <p class="mt-3 text-muted">{{event.short_description|truncatewords:15}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% empty %}
            <div class="col">
                <h5 class="text-muted">No Events found. Please visit us later.</h5>
            </div>
            {% endfor %}
        </div>
        {% if not_running_events %}
        <div class="row mt-5">
            <div class="col">
                <h1>Other Events</h1>
            </div>
        </div>
        <div class="row mt-3">
            {% for event in not_running_events %}
            <div class="col-xs-12 col-sm-6 mb-4 blog-showcase">
                <a href="{{event.get_absolute_url}}">
                    <div class="content-box boxed blog-box">
                        <div style="position: relative;">
                            <img src="{{event.image.url}}" class="blog-image" alt="{{blog.title}}">
                            <div class="blog-date">
                                <span>{{event.start_date|date:"d"}}</span>
                                <span>{{event.start_date|date:"M Y"}}</span>
                            </div>
                        </div>
                        <div class="p-3">
                            <h4 class="mb-3">{{event.name}}</h4>
                            <i class="fas fa-bookmark"></i>
                            <span class="ml-1 mr-5">
                                {% for place in event.place.all %}
                                <span class="event_places">{{place.name}}</span>
                                {% endfor %}
                            </span>
                            <i class="fas fa-calendar"></i> <span>{{event.duration}} Days</span>
                            <p class="mt-3 text-muted">{{event.short_description|truncatewords:15}}</p>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</section>
{% endblock %}

{% block script_links %}
{% endblock %}

{% block scripts %}
{% endblock %}

templates/home/coming-soon.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | Home {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
{% endblock %}


{% block content %}

<div class="page-wrapper">
    <div class="overlay"></div>
    <div class="container">
        <div class="row pt-5">
            <div class="col d-flex flex-column align-items-center">
                <p class="text-center">आर्थिक उन्नतिको लागि पर्यटन, पर्यटनका लागि</p>
                <!-- <p class="text-uppercase text-center">पर्यटकिय चक्रपथ</p> -->
                <h1 class="coming-soon__title text-center">
                    सांस्कृतिक चक्रपथ
                </h1>
                <p class="text-center">प्रतिक्षा गर्नुहोस</p>

                <!-- <p class="mt-5 text-center">This website is under construction and will be launched in </p> -->
            </div>
        </div>
        <div class="row time__wrapper d-flex flex-row justify-content-center">
            <div class="col-xs-4 col-sm-4 col-md-auto d-flex flex-column align-items-center timer">
                <div class="time" id="timer-days">00</div>
                <div class="time-label">दिन</div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-auto d-flex flex-column align-items-center timer">
                <div class="time" id="timer-hours">00</div>
                <div class="time-label">घण्टा</div>
            </div>
            <div class="col-xs-4 col-sm-4 col-md-auto d-flex flex-column align-items-center timer">
                <div class="time" id="timer-minutes">00</div>
                <div class="time-label">मिनेट</div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-auto d-flex flex-column align-items-center timer">
                <div class="time" id="timer-seconds">00</div>
                <div class="time-label">सेकेन्ड</div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-auto d-flex flex-column align-items-center timer">
                <div class="time" id="timer-ms">00</div>
                <div class="time-label">मिलिसेकेन्ड</div>
            </div>
        </div>
        <div class="row">
            <div class="col d-flex flex-row justify-content-center fixed-bottom mb-3">
                Made with <span class="mx-1" style="color: red">&hearts;</span> from <a class="ml-1"
                    href="https://techkunja.com.np" target="_blank">Tech Kunja</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script_links %}

{% endblock %}

{% block scripts %}
<script>
    var now = new Date().getTime();
    var launchDate = new Date("{{launchDate}}").getTime();
    var difference = launchDate - now
    $days = $('#timer-days');
    $hours = $('#timer-hours');
    $minutes = $('#timer-minutes');
    $seconds = $('#timer-seconds');
    $ms = $('#timer-ms');

    // var engStr = "1";

    function converter(str) {
        strStr = String(str);
        var nepStr = '';
        for (let i = 0; i < strStr.length; i++) {
            switch (strStr[i]) {
                case '0':
                    nepStr += '०';
                    break;
                case '1':
                    nepStr += '१';
                    break;
                case '2':
                    nepStr += '२';
                    break;
                case '3':
                    nepStr += '३';
                    break;
                case '4':
                    nepStr += '४';
                    break;
                case '5':
                    nepStr += '५';
                    break;
                case '6':
                    nepStr += '६';
                    break;
                case '7':
                    nepStr += '७';
                    break;
                case '8':
                    nepStr += '८';
                    break;
                case '9':
                    nepStr += '९';
                    break;

            }
        }
        return nepStr;
    }

    function printTime() {
        var now = new Date().getTime();
        var launchDate = new Date("{{launchDate}}").getTime();
        var diff = launchDate - now;
        $('#test-time').html(now.toString());
        setTimeout(function () {
            if (diff > 0) {
                diff -= 76;
                printTime();
                $ms.text(converter(new Date(diff).getMilliseconds().toString().padStart(3, "0")));
                $seconds.text(converter(new Date(diff).getSeconds().toString().padStart(2, "0")));
                $minutes.text(converter(new Date(diff).getMinutes().toString().padStart(2, "0")));
                $hours.text(converter(new Date(diff).getHours().toString().padStart(2, "0")));
                let days = Math.floor(new Date(diff) / (1000 * 60 * 60 * 24)).toString().padStart(2, "0");
                $days.text(converter(days));
            }
        }, 76);
    }

    printTime();
</script>

{% endblock %}

templates/home/gallery.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | Video Gallery {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
{% endblock %}


{% block content %}
<section class="bg-light page-content__wrapper">
    <div class="container pt-5">
        <div class="row">
            <div class="col">
                <h1>Video Gallery</h1>
            </div>
        </div>
        <div class="row mt-3">
            {% for gallery in gallery %}
            <div class="col-xs-12 col-md-6 mb-4">
                <iframe width="560" height="315" src="{{gallery.video_url}}" frameborder="0"
                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock %}

{% block script_links %}
{% endblock %}

{% block scripts %}
{% endblock %}

templates/home/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | Home {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
{% endblock %}


{% block content %}
<div class="owl-carousel owl-theme">
    {% for slider in slider_list %}
    <div class="item">
        <div class="slider-overlay"></div>
        <img class="slider-image" src="{{slider.image.url}}" alt="{{slider.caption}}">
        <div class="slider-caption">
            <div class="slider-caption__inner">
                <h2 class="text-center mb-0">
                    {{slider.caption}}
                </h2>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="container mt-5">
    <!-- <div class="row">
        <div class="col">
            <h3 class="text-center">About</h3>
            <p class="text-center">{{about.short_content}}</p>
        </div>
    </div> -->
    <div class="row mt-5">
        <div class="col">
            <!-- <h3 class="text-center">Places</h3> -->
            <p class="text-center">{{about.short_content}}</p>
        </div>
    </div>
    <div class="row my-5">
        {% for place in places %}
        <div class="col-xs-12 col-md-4">
            <div class="card place-card mb-3">
                <img class="card-img-top card-image" src="{{place.image.url}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{place.name}}</h5>
                    <p class="card-text">{{place.short_description|truncatewords:30}}</p>
                    <a href="{{place.get_absolute_url}}" class="btn btn-outline-primary">Read More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<!-- <div class="container-fluid place-wrapper my-5">
    <div class="row">
        <div class="col place-container__text-wrapper">text</div>
        <div class="col">image</div>
    </div>
</div> -->
{% endblock %}

{% block script_links %}
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
{% endblock %}

{% block scripts %}

<script>
    $('.owl-carousel').owlCarousel({
        loop: true,
        margin: 10,
        nav: false,
        items: 1,
        autoplay: true,
        autoplayHoverPause: true,

    })
</script>
{% endblock %}

templates/place/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | {{instance.name}} {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
{% endblock %}


{% block content %}
<section class="page-content__wrapper">
    <img src="{{instance.image.url}}" alt="{{instance.name}}" class="place-page-image">
    <div class="lang-btns">
        <div class="btn-group btn-group-sm" role="group">
            <button type="button" class="btn btn-primary" id="engBtn">Eng</button>
            <button type="button" class="btn btn-outline-primary" id="nepBtn">नेपाली</button>
        </div>
    </div>
    <div class="container pt-3">
        <div class="row mt-3">
            <div class="col" id="main-content">
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block script_links %}
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        var $engBtn = $('#engBtn');
        var $nepBtn = $('#nepBtn');
        var $mainContent = $('#main-content');
        var safeContentEng = `{{instance.long_description|safe}}`
        var safeContentNep = `{{instance.long_description_nepali|safe}}`
        $mainContent.html(safeContentEng);
        $engBtn.on({
            click: function () {
                $(this).removeClass("btn-outline-primary");
                $(this).addClass("btn-primary");
                $nepBtn.addClass("btn-outline-primary");
                $nepBtn.removeClass("btn-primary");
                $mainContent.html(safeContentEng);
                console.log("eng clicked");
            }
        });
        $nepBtn.on({
            click: function () {
                $(this).removeClass("btn-outline-primary");
                $(this).addClass("btn-primary");
                $engBtn.addClass("btn-outline-primary");
                $engBtn.removeClass("btn-primary");
                $mainContent.html(safeContentNep);
                console.log("nep clicked")
            }
        });
    });
</script>
{% endblock %}

templates/place/place.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Cultural Ring Road | Places {% endblock %}
{% block meta_links %}

<!-- put meta stuffs here -->
{% endblock %}

{% block style_links %}
{% endblock %}


{% block content %}
<div class="container pt-5 page-content__wrapper">
    <div class="row my-5">
        {% for place in places %}
        <div class="col-xs-12 col-md-4">
            <div class="card place-card mb-3">
                <img class="card-img-top card-image" src="{{place.image.url}}" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">{{place.name}}</h5>
                    <p class="card-text">{{place.short_description|truncatewords:30}}</p>
                    <a href="{{place.get_absolute_url}}" class="btn btn-outline-primary">Read More</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block script_links %}
{% endblock %}

{% block scripts %}
{% endblock %}